# Generated by Django 4.0.2 on 2022-02-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('short_url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostRequestsToUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=1000)),
                ('referer', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_url.url')),
            ],
        ),
        migrations.CreateModel(
            name='CountRequestsToShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_url.url')),
            ],
        ),
    ]
